### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [jasonbking/sauth#1]
for this one:
```js
             // INSERT into users
                queries.push(t.none(sql.add, user));

                // INSERTs into user_group if needed
                ga.forEach(groupUuid =>
                    queries.push(t.none(sql.addGroup,
                        [ accountUuid, userUuid, groupUuid ])));

                return t.batch(queries);
                // XXX: It'd be nice to return the
                // resulting user JSON
```
changing the last line to this should do it:
```js
return t.batch(queries).then(a=>a[0]);
```
if I understood it right ;) but you would need to return the user record (use `RETURNING *` and the use method `one`), then you can have you user's JSON :wink:

**Comment by jasonbking** [comment]
Ahh cool.  Though I realized I pretty much have all the data already and can just return that after the query completes (the assumption being that any errors will go through .catch(...)).  But very cool of you to take such quick notice, thanks! :)
